// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZulAi.Infrastructure.Data;

#nullable disable

namespace ZulAi.Infrastructure.Migrations
{
    [DbContext(typeof(ZulAiDbContext))]
    partial class ZulAiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZulAi.Domain.Entities.Atom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Energy")
                        .HasColumnType("double");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("PositionX")
                        .HasColumnType("double");

                    b.Property<double>("PositionY")
                        .HasColumnType("double");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UniverseStateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UniverseStateId", "IsAlive");

                    b.ToTable("Atoms");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.AtomConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SourceAtomId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Strength")
                        .HasColumnType("double");

                    b.Property<Guid>("TargetAtomId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TickFormed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceAtomId");

                    b.HasIndex("TargetAtomId");

                    b.ToTable("AtomConnections");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.GeneratedOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AsciiArt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AtomCount")
                        .HasColumnType("int");

                    b.Property<int>("ConnectionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GridHeight")
                        .HasColumnType("int");

                    b.Property<int>("GridWidth")
                        .HasColumnType("int");

                    b.Property<int>("Tick")
                        .HasColumnType("int");

                    b.Property<Guid>("UniverseStateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UniverseStateId", "Tick")
                        .IsUnique();

                    b.ToTable("GeneratedOutputs");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AtomId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Tick")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UniverseStateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UniverseStateId", "Tick");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.UniverseState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentTick")
                        .HasColumnType("int");

                    b.Property<int>("GridHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(40);

                    b.Property<int>("GridWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(80);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastTickAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("UniverseStates");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.Atom", b =>
                {
                    b.HasOne("ZulAi.Domain.Entities.UniverseState", "UniverseState")
                        .WithMany("Atoms")
                        .HasForeignKey("UniverseStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniverseState");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.AtomConnection", b =>
                {
                    b.HasOne("ZulAi.Domain.Entities.Atom", "SourceAtom")
                        .WithMany("ConnectionsAsSource")
                        .HasForeignKey("SourceAtomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulAi.Domain.Entities.Atom", "TargetAtom")
                        .WithMany("ConnectionsAsTarget")
                        .HasForeignKey("TargetAtomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceAtom");

                    b.Navigation("TargetAtom");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.GeneratedOutput", b =>
                {
                    b.HasOne("ZulAi.Domain.Entities.UniverseState", "UniverseState")
                        .WithMany("Outputs")
                        .HasForeignKey("UniverseStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniverseState");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("ZulAi.Domain.Entities.UniverseState", "UniverseState")
                        .WithMany("Interactions")
                        .HasForeignKey("UniverseStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniverseState");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.Atom", b =>
                {
                    b.Navigation("ConnectionsAsSource");

                    b.Navigation("ConnectionsAsTarget");
                });

            modelBuilder.Entity("ZulAi.Domain.Entities.UniverseState", b =>
                {
                    b.Navigation("Atoms");

                    b.Navigation("Interactions");

                    b.Navigation("Outputs");
                });
#pragma warning restore 612, 618
        }
    }
}
